#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <cstring>
#include <gl/glew.h>
#include "CppWarn.h"
#include "TypeDefs.h"
#include "Core/Debug/Assert.h"
#include "Core/Standard/Color.h"
#include "Core/Standard/String.h"
#include "Core/Standard/Array.h"
#include "Core/Math/Math.h"
#include "Core/Math/Vector.h"
#include "Core/Math/Quat.h"
#include "Core/Time/Time.h"
#include "Core/Defer.h"
#include "Core/Memory/TempStack.h"
#include "Core/Delegate/Delegate.h"
#include "Core/Delegate/Event.h"